config/routes.rb
Reddit::Application.routes.draw do

  root to: 'sign_ins#new'

  resources :users, only: [:new, :create, :show]
  resources :sign_ins, only: [:new, :create, :destroy]

  resources :subs, except: :destroy do
    member do
      resources :posts, only: :new
    end
  end

  resources :posts, except: [:new, :destroy, :index] do
    member do
      resources :comments, only: :new
    end
  end

  resources :comments, only: :create do
    member do
      get 'nested_comments' => 'comments#new_nested', as: 'new_nested'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :author, :post

  belongs_to :author, class_name: 'User', inverse_of: :comments
  belongs_to :post, inverse_of: :comments

  belongs_to :parent_comment,
  class_name: 'Comment',
  inverse_of: :child_comments

  has_many :child_comments,
  class_name: 'Comment',
  foreign_key: :parent_comment_id,
  inverse_of: :parent_comment
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Post.find(params[:id]).comments.new
    render :new
  end

  def new_nested
    parent = Comment.find(params[:id])
    @comment = parent.child_comments.new(post_id: parent.post_id)
    render :new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      render :new
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:post_id, :parent_comment_id, :content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li>
  Comment by <%= "#{comment.author.name} " +
  "#{distance_of_time_in_words(comment.created_at, Time.now)} ago" %><br>
  <%= comment.content %><br>
  <%= link_to "Reply", new_nested_comment_url(comment)  %>
</li>
<% unless comments_by_parent_id[comment.id].empty? %>
<ul>
  <% comments_by_parent_id[comment.id].each do |child_comment| %>
    <%= render 'comments/comment', comment: child_comment,
      comments_by_parent_id: comments_by_parent_id %>
  <% end %>
</ul>
<% end %>

app/views/comments/new.html.erb
<h1>Add a comment</h1>

<form action="<%= comments_url %>" method="POST">
  <%= auth_input %>
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <input type="hidden" name="comment[parent_comment_id]"
    value="<%= @comment.parent_comment_id %>">

  <p>
    <label for="comment_content">What's on your mind?</label><br>
    <textarea name="comment[content]" id="comment_content"></textarea>
  </p>

  <button>Post comment</button>
</form>