config/routes.rb
Reddit::Application.routes.draw do

  root to: 'sign_ins#new'

  resources :users, only: [:new, :create, :show]
  resources :sign_ins, only: [:new, :create, :destroy]

  resources :subs, except: :destroy do
    member do
      resources :posts, only: :new
    end
  end

  resources :posts, except: [:new, :destroy, :index] do
    member do
      resources :comments, only: :new
    end
  end

  resources :comments, only: :create do
    member do
      get 'nested_comments' => 'comments#new_nested', as: 'new_nested'
    end
  end

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates_presence_of :title, :description, :moderator_id
  validates_uniqueness_of :title

  belongs_to :moderator, class_name: "User", inverse_of: :subs
  has_many :sub_posts, inverse_of: :sub
  has_many :posts, through: :sub_posts, source: :post

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_filter :ensure_signed_in, except: [:index, :show]
  before_filter :ensure_mod_of_sub, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = current_user.subs.new(sub_params)

    if @sub.save
      redirect_to sub_url(@sub)
    else
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end


  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def ensure_mod_of_sub
    sub = Sub.find(params[:id])
    if sub.nil? || current_user != sub.moderator
      redirect_to :back
    end
  end

end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<form action="<%= form_action %>" method="POST">
  <%= auth_input %>
  <%= put_method if form_method == :put %>

  <% unless sub.title %>
  <p>
    <label for="sub_title">Title</label><br>
    <input type="text" name="sub[title]" id="sub_title">
  </p>
  <% end %>
  <p>
    <label for="sub_description">Description</label><br>
    <textarea name="sub[description]"
      id="sub_description"><%= sub.description %></textarea>
  </p>

  <button><%= button_verb %> subreddit</button>
</form>

app/views/subs/edit.html.erb
<h1>Change <%= @sub.title %></h1>

<%= render 'form',
  sub: @sub,
  form_action: sub_url(@sub),
  form_method: :put,
  button_verb: "Change" %>

app/views/subs/index.html.erb
<h1>Subreddits</h1>

<% @subs.each do |sub| %>
<p>
  <%= link_to sub.title, sub_url(sub) %><br>
  <%= sub.description %>
</p>
<% end %>

<p>
  <%= link_to "Add new subreddit", new_sub_url %>
</p>

app/views/subs/new.html.erb
<h1>Make a new subreddit</h1>

<%= render 'form',
  sub: @sub,
  form_action: subs_url,
  form_method: :post,
  button_verb: "Create" %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p>Mod: <%= link_to @sub.moderator.name, user_url(@sub.moderator) %></p>

<ul>
<% @sub.posts.each do |post| %>
  <li><%= link_to post.title, post_url(post) %></li>
<% end %>
</ul>

<p>
  <%= link_to "add post", new_post_url(@sub) %><br>
  <%= link_to "all subreddits", subs_url %>
</p>