config/routes.rb
Reddit::Application.routes.draw do

  root to: 'sign_ins#new'

  resources :users, only: [:new, :create, :show]
  resources :sign_ins, only: [:new, :create, :destroy]

  resources :subs, except: :destroy do
    member do
      resources :posts, only: :new
    end
  end

  resources :posts, except: [:new, :destroy, :index] do
    member do
      resources :comments, only: :new
    end
  end

  resources :comments, only: :create do
    member do
      get 'nested_comments' => 'comments#new_nested', as: 'new_nested'
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :author_id

  belongs_to :author, class_name: "User", inverse_of: :posts
  has_many :sub_posts, inverse_of: :post
  has_many :subs, through: :sub_posts, source: :sub

  has_many :comments, inverse_of: :post
  has_many :top_level_comments,
  -> { where("parent_comment_id IS NULL") },
  class_name: 'Comment'

  def comments_by_parent_id
    comments_by_parent_id = Hash.new([])
    self.comments.includes(:author).each do |comment|
      comments_by_parent_id[comment.parent_comment_id] += [comment]
    end

    comments_by_parent_id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :ensure_signed_in, except: :show
  before_filter :ensure_author_of_post, only: [:edit, :update]

  def new
    @post = Sub.find(params[:id]).posts.new
    render :new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments_by_parent_id = @post.comments_by_parent_id
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      render :edit
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, { sub_ids: [] })
  end

  def ensure_author_of_post
    post = Post.find(params[:id])
    if post.nil? || current_user != post.author
      render ({
        text: "YOU'RE TRYING TO MESS UP SOMEONE ELSE'S STUFF",
        status: :forbidden
      })
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<form action="<%= form_action %>" method="POST">
  <%= auth_input %>

  <%= put_input if form_method == :put %>

  <p>
    <label for="post_title">Title</label><br>
    <input type="text" name="post[title]"
      id="post_title" value="<%= post.title %>">
  </p>

  <p>
    <label for="post_url">URL</label><br>
    <input type="text" name="post[url]"
      id="post_url" value="<%= post.url %>">
  </p>

  <p>
    <label for="post_content">Content</label><br>
    <textarea name="post[content]"
      id="post_content"><%= post.content %></textarea>
  </p>

  <p>
    <label for="post_sub_ids">Post to:</label><br>
    <% Sub.all.each do |sub| %>
      <input type='checkbox'
             name='post[sub_ids][]'
             id="post_sub_ids_<%= sub.title %>"
             value="<%= sub.id %>"
             <%= "checked" if post.sub_posts.map(&:sub).include?(sub) %>>
      <label for="post_sub_ids_<%= sub.title %>"><%= sub.title %></label><br>
    <% end %>
  </p>

  <button><%= button_verb %> it!</button>
</form>

app/views/posts/edit.html.erb
<h1>Change <%= @post.title %></h1>

<%= render 'form',
  post: @post,
  form_action: post_url(@post),
  form_method: :put,
  button_verb: "Change" %>

app/views/posts/new.html.erb
<h1>Add a new post</h1>

<%= render 'form',
  post: @post,
  form_action: posts_url,
  form_method: :post,
  button_verb: "Post" %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p>
  <%= link_to @post.url, @post.url %>
</p>
<p>
  <%= @post.content %>
</p>

<% unless @comments_by_parent_id[nil].empty? %>
  <h2>Comments</h2>
  <ul>
    <% @comments_by_parent_id[nil].each do |comment| %>
      <% next unless comment.parent_comment_id.nil? %>
      <%= render 'comments/comment', comment: comment,
        comments_by_parent_id: @comments_by_parent_id %>
    <% end %>
  </ul>
<% end %>

<p>
  <%= link_to("Edit post<br>".html_safe, edit_post_url(@post)) \
    if @post.author == current_user %>
  <%= link_to("Add comment<br>".html_safe, new_comment_url(@post)) \
    if signed_in? %>
  <% @post.subs.each do |sub| %>
    <%= link_to "Back to #{sub.title}", sub_url(sub) %><br>
  <% end %>
</p>